name: "Code Check"

on:
  push:
    branches:
      - master
      - "1.12.2"
  pull_request:

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip codecheck]') || contains(github.event.head_commit.message, '[skip codecheck editorconfig]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: EditorConfig Audit
        uses: zbeekman/EditorConfig-Action@v1.1.1
        env:
          ALWAYS_LINT_ALL_FILES: true
          EC_FIX_ERROR: false
